companies:
  - 'amil'
  - 'bradesco'
  - 'porto'
  - 'sulamerica'
  - 'unimed'
appstoreapps: 
  - 'amil-clientes'
  - 'bradesco-saúde'
  - 'porto-saúde'
  - 'sulamérica-saúde'
  - 'unimed-cliente'
googleplayapps:
  - 'br.com.amil.beneficiarios'
  - 'br.com.bradseg.segurobradescosaude'
  - 'br.com.portoseguro.saudeodonto'
  - 'br.com.sulamerica.sam.saude'
  - 'br.com.app.centralnacionalunimed'
country: 'br'
language: 'pt-br'
storeid: 'store_id'
renamedcolumns:
  at: 'date'
  content: 'review'
  score: 'rating'
selectedcolumns:
  - 'userName'
  - 'date'
  - 'company'
  - 'store_id'
  - 'review'
  - 'rating'
textcolumn: 'review'